# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  JiraUpdaterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          JIRA_BASE_URL: "{{resolve:secretsmanager:MySecretName:SecretString:api_key}}"
          JIRA_TOKEN: "{{resolve:secretsmanager:MySecretName:SecretString:api_key}}"
          OPENAI_API: "{{resolve:secretsmanager:MySecretName:SecretString:api_key}}"
      Events:
        JiraUpdaterGateway:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /updatejira
            Method: put
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./jiraupdaterlambda
      DockerTag: python3.11-v1
